### ISSUE TITLE
Cannot register MFA

### ISSUE THREAD

**Issue by TheGameFreak720** [sn-extensions/mfa-link#21]
Fedora release 32 (Thirty Two)
Mozilla Firefox 88.0

When registering MFA on the web application I copy the code to my clipboard and register the new app using authy, after pasting my secret key and adding my generated code the button won't do anything until the code expires, and then an alert shows up saying the code is invalid. I haven't been able to add MFA since I paid for the extensions.

**Comment by atmoio** [comment]
Sorry about that, we're in the midst of a large-scale server deployment right now, and we expect this issue to be resolved within the day. Will update this thread.

**Comment by TheGameFreak720** [comment]
Np, just wanted to let you know since I saw the same problem on this repo when I was trying to figure out why is it so small on desktop hence a PR for accessibility purposes. No rush since my app is still pretty secure

**Comment by atmoio** [comment]
I've tested this now and was unable to reproduce the issue. Perhaps not server related after all. Can you try this again?

**Comment by TheGameFreak720** [comment]
Is it safe to record those creds and include a video of the behavior? I can try again and if I reproduce I can send a vid

**Comment by atmoio** [comment]
Yes safe to record as long as you end up discarding those 2FA credentials.

**Comment by TheGameFreak720** [comment]
This time because I had to return my Fedora computer I'm trying on Windows 10 with Firefox Browser.

Looking at my console saw this error `Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://extensions.standardnotes.org’) does not match the recipient window’s origin (‘https://app.standardnotes.org’).`

The following is the behavior I get with the video:

* Clicking the install 2FA doesn't work and will only throw an alert after the code changes
* Mentions something about `https://extensions.standardnotes.org`, but that URL is down or doesn't exist. See screenshot.
* The 2FA modal in desktop is very small, and I have to scroll down to move the screen, then up. Awful UX. 

https://user-images.githubusercontent.com/20229602/119009722-6c027a00-b961-11eb-81f0-f52b8b20a039.mp4

![firefox_1JHuyNhB6O](https://user-images.githubusercontent.com/20229602/119010144-c1d72200-b961-11eb-8b24-52fc43fae6a7.png)

**Comment by atmoio** [comment]
The postMessage issue appears when either of the URLs fail to load, like extensions.standardnotes.org or app.standardnotes.org. Does extensions.standardnotes.org work in your browser? If it is working now, try 2FA set up again and see if that works. You should be able to verify it's working without having to go through the whole setup: simply see if the 2FA window sizes itself properly. If it does, this means the window and SN are able to talk to each other. If not, it means the issue persists.

**Comment by TheGameFreak720** [comment]
The window has been resized, and I was able to register my MFA device. Not providing screenshots since that would expose my secret key. Thanks for all the help
